# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2.0
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build Image
          command: |
            SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            docker build -t whizus/laravel-test:$SHORT_GIT_HASH .
            docker push whizus/laravel-test:$SHORT_GIT_HASH

            
workflows:
  version: 2
  build-and-test:
    jobs:
      - build