kind: Service
apiVersion: v1
metadata:
  name: laravel-php-example-service
spec:
  selector:
    app: laravel-php-example
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-php-example
  labels:
    app: laravel-php-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-php-example
  template:
    metadata:
      labels:
        app: laravel-php-example
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: php
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
- containerPort: 80